---

- hosts: localhost
  become: true
  tasks:

  - name: Install Apache and PHP packages for Ubuntu
    package:
      name:
        - apache2
        - libapache2-mod-php
      state: latest

  - name: Install Apache and PHP packages for CentOS
    package:
      name:
        - httpd
        - php
      state: latest
